spring.application.name=account_manager

spring.datasource.url=jdbc:postgresql://localhost:5432/account_manager
spring.datasource.password=1803vesna
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update