CREATE TABLE profile
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profile_name VARCHAR(50),
    username     VARCHAR(50),
    password     VARCHAR(50),
    CONSTRAINT pk_profile PRIMARY KEY (id)
);